### ISSUE TITLE
Trees missing in 1.3.0

### ISSUE THREAD

**Issue by jaraco** [python/importlib_resources#88]
In GitLab by @henryiii on Mar 6, 2020, 15:19

I just merged a PR that worked with 1.2.0 and in master it built with 1.3.0, and I get ` AttributeError: 'module' object has no attribute 'trees'` (using exactly what is in the documentation).

https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename

**Comment by jaraco** [comment]
In GitLab by @henryiii on Mar 6, 2020, 15:20

* Before: https://travis-ci.com/scikit-hep/scikit-hep-testdata/builds/152051922
* After:  https://travis-ci.com/scikit-hep/scikit-hep-testdata/builds/152208999

**Comment by jaraco** [comment]
In GitLab by @henryiii on Mar 6, 2020, 15:23

changed the description

**Comment by jaraco** [comment]
In GitLab by @henryiii on Mar 6, 2020, 15:30

FYI, I've worked around it for now, but it's bad that the documentation refers to things now moved.

https://github.com/scikit-hep/scikit-hep-testdata/pull/27

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 6, 2020, 16:28

That's a mistake. I created a `trees` module to maintain compatibility but probably forgot to add it.

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 6, 2020, 16:28

I'll have a fix shortly.

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 6, 2020, 16:34

I thought I'd updated the docs to reflect the preferred usage. I guess I missed that in a couple of places too.

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 6, 2020, 16:35

closed via commit 3b5d3455e6466fb9046a729e3828a7ff8ea8bc0a

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 6, 2020, 16:35

This should be fixed in 1.3.1, rolling out now.

**Comment by jaraco** [comment]
In GitLab by @jaraco on Mar 19, 2020, 23:10

mentioned in commit 3b5d3455e6466fb9046a729e3828a7ff8ea8bc0a
